queue_rules:
  - name: default
    allow_inplace_checks: false
    queue_conditions:
      - and:
        - "#approved-reviews-by>=0"
        - "check-success=tests"
    merge_conditions:
      - "check-success=tests"
